//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArturCzarnecki_9807
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemSWPF : DbContext
    {
        public SystemSWPF()
            : base("name=SystemSWPF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fizjoterapeuta> Fizjoterapeuta { get; set; }
        public virtual DbSet<Gabinet> Gabinet { get; set; }
        public virtual DbSet<Godziny> Godziny { get; set; }
        public virtual DbSet<KodPocztowy> KodPocztowy { get; set; }
        public virtual DbSet<Pacjent> Pacjent { get; set; }
        public virtual DbSet<Rola> Rola { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Wizyta> Wizyta { get; set; }
    }
}
