//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArturCzarnecki_9807
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pacjent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacjent()
        {
            this.Wizyta = new HashSet<Wizyta>();
        }
    
        public int IdPacjenta { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Haslo { get; set; }
       
        public string Imie { get; set; }
   
        public string Nazwisko { get; set; }
   
        public string KodPocztowy { get; set; }
  
        public string Miasto { get; set; }
        
        public string Ulica { get; set; }
     
        public string Lokal { get; set; }
 
        public string NrTelefonu { get; set; }
        public int IdRoli { get; set; }
    
        public virtual Rola Rola { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wizyta> Wizyta { get; set; }
    }
}
